### ISSUE TITLE
Save / Load

### ISSUE THREAD

**Issue by 0b5vr** [FMS-Cat/nightbird#1]
- save selected nodes as json
- and also load from json
- what properties of nodes it needs to save?
- how to load local glsl/gif when it loads? it seems impossible to me
- i think it should be done without server

**Comment by mactkg** [comment]
@FMS-Cat 
You can use check list like this!
- [x] Buy a cat food
- [ ] Eat a cat food

syntax:

```
- [ ] Buy a cat food
- [ ] Eat a cat food 
```

**Comment by 0b5vr** [comment]
@mactkg いいですね！

**Comment by FMS-Cat** [comment]
FileSystem APIどうでしょう
>tkgdisco: [at]FMS_Cat http://t.co/wM40dI9l4D

**Comment by 0b5vr** [comment]
FileSystem APIどうでしょう

> tkgdisco: [at]FMS_Cat http://t.co/wM40dI9l4D

**Comment by 0b5vr** [comment]
設定用JSON + バイナリファイルを縦につなげただけのバイナリファイル（.nightbird）を作成して解決
